import {
  PostRegister,
  RegisterVerifyOtp,
  RegisterResendOtp,
} from './PostRegister';
import { Login } from './Login';
import {
  GetMaterialCollectionData,
  GetMyMaterialCollectionData,
  GetMaterialCollectionDetailData,
  PurchaseMaterialCollection,
  GetMaterialDetailData,
  GetLastReadMaterialCollectionDetailData,
} from './Material';
import {
  GetLatestForumData,
  GetTrendingForumData,
  GetComments,
  AddComments,
  AddPost,
} from './Forum';
import { GetProductList, GetProductDetailData, PurchaseProduct, GetHistoryList, CheckStatus } from './Product';
import {
  GetAllExercisesSetData,
  GetMyExercisesSetData,
  GetExercisesSetDetailData,
  GetExercisesDetailContent,
  StartNewAttempt,
  SubmitAnswer,
  SubmitAttempt,
  GetAttemptList,
  GetComingSoonExercise,
  PurchaseExercise,
} from './Exercises';
import {
  GetAllTryOutData,
  GetMyTryOutData,
  GetTryOutDetailData,
  PurchaseTryout,
  GetAttemptListTryout,
  GetTryoutQuestionDetail,
  StartNewAttemptTryOut,
  SubmitTryoutAnswer,
  SubmitTryOutAttempt,
  GetComingSoonTryout,
} from './TryOut';

export const ActionStudent = {
  PostRegister,
  RegisterVerifyOtp,
  RegisterResendOtp,
  Login,
  GetLatestForumData,
  GetTrendingForumData,
  GetComments,
  AddComments,
  AddPost,
  GetMaterialCollectionData,
  GetMyMaterialCollectionData,
  GetMaterialCollectionDetailData,
  PurchaseMaterialCollection,
  GetMaterialDetailData,
  GetLastReadMaterialCollectionDetailData,
  GetAllExercisesSetData,
  GetMyExercisesSetData,
  GetExercisesSetDetailData,
  GetExercisesDetailContent,
  StartNewAttempt,
  SubmitAnswer,
  SubmitAttempt,
  GetAttemptList,
  PurchaseExercise,
  GetComingSoonExercise,
  GetAllTryOutData,
  GetMyTryOutData,
  GetTryOutDetailData,
  StartNewAttemptTryOut,
  PurchaseTryout,
  GetAttemptListTryout,
  GetTryoutQuestionDetail,
  SubmitTryoutAnswer,
  SubmitTryOutAttempt,
  GetComingSoonTryout,
  GetProductList,
  GetProductDetailData,
  PurchaseProduct,
  GetHistoryList,
  CheckStatus
};
