// POST_REGISTER //
export const POST_REGISTER_REQUEST = 'POST_REGISTER_REQUEST';
export const POST_REGISTER_SUCCESS = 'POST_REGISTER_SUCCESS';
export const POST_REGISTER_FAILED = 'POST_REGISTER_FAILED';

// REGISTER_VERIFY_OTP //
export const REGISTER_VERIFY_OTP_REQUEST = 'REGISTER_VERIFY_OTP_REQUEST';
export const REGISTER_VERIFY_OTP_SUCCESS = 'REGISTER_VERIFY_OTP_SUCCESS';
export const REGISTER_VERIFY_OTP_FAILED = 'REGISTER_VERIFY_OTP_FAILED';

// RESEND_OTP_REGISTER //
export const RESEND_OTP_REGISTER_REQUEST = 'RESEND_OTP_REGISTER_REQUEST';
export const RESEND_OTP_REGISTER_SUCCESS = 'RESEND_OTP_REGISTER_SUCCESS';
export const RESEND_OTP_REGISTER_FAILED = 'RESEND_OTP_REGISTER_FAILED';

// LOGIN //
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// GET_LATEST_FORUM_DATA //
export const GET_LATEST_FORUM_DATA_REQUEST = 'GET_LATEST_FORUM_DATA_REQUEST';
export const GET_LATEST_FORUM_DATA_SUCCESS = 'GET_LATEST_FORUM_DATA_SUCCESS';
export const GET_LATEST_FORUM_DATA_FAILED = 'GET_LATEST_FORUM_DATA_FAILED';

// GET_TRENDING_FORUM_DATA //
export const GET_TRENDING_FORUM_DATA_REQUEST =
  'GET_TRENDING_FORUM_DATA_REQUEST';
export const GET_TRENDING_FORUM_DATA_SUCCESS =
  'GET_TRENDING_FORUM_DATA_SUCCESS';
export const GET_TRENDING_FORUM_DATA_FAILED = 'GET_TRENDING_FORUM_DATA_FAILED';

// GET_COMMENTS //
export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAILED = 'GET_COMMENTS_FAILED';

// ADD_COMMENT //
export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILED = 'ADD_COMMENT_FAILED';

// ADD_POST //
export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAILED = 'ADD_POST_FAILED';

// GET_MATERIAL_COLLECTION //
export const GET_MATERIAL_COLLECTION_REQUEST =
  'GET_MATERIAL_COLLECTION_REQUEST';
export const GET_MATERIAL_COLLECTION_SUCCESS =
  'GET_MATERIAL_COLLECTION_SUCCESS';
export const GET_MATERIAL_COLLECTION_FAILED = 'GET_MATERIAL_COLLECTION_FAILED';

// GET_MY_MATERIAL_COLLECTION //
export const GET_MY_MATERIAL_COLLECTION_REQUEST =
  'GET_MY_MATERIAL_COLLECTION_REQUEST';
export const GET_MY_MATERIAL_COLLECTION_SUCCESS =
  'GET_MY_MATERIAL_COLLECTION_SUCCESS';
export const GET_MY_MATERIAL_COLLECTION_FAILED =
  'GET_MY_MATERIAL_COLLECTION_FAILED';

// GET_MATERIAL_COLLECTION_DETAIL_DATA //
export const GET_MATERIAL_COLLECTION_DETAIL_DATA_REQUEST =
  'GET_MATERIAL_COLLECTION_DETAIL_DATA_REQUEST';
export const GET_MATERIAL_COLLECTION_DETAIL_DATA_SUCCESS =
  'GET_MATERIAL_COLLECTION_DETAIL_DATA_SUCCESS';
export const GET_MATERIAL_COLLECTION_DETAIL_DATA_FAILED =
  'GET_MATERIAL_COLLECTION_DETAIL_DATA_FAILED';

// GET_PRODUCT_LIST_DATA //
export const GET_PRODUCT_LIST_DATA_REQUEST = 'GET_PRODUCT_LIST_DATA_REQUEST';
export const GET_PRODUCT_LIST_DATA_SUCCESS = 'GET_PRODUCT_LIST_DATA_SUCCESS';
export const GET_PRODUCT_LIST_DATA_FAILED = 'GET_PRODUCT_LIST_DATA_FAILED';

// RESET_STATE //
export const RESET_COMMENTS_STATE = 'RESET_COMMENTS_STATE';
export const RESET_REGISTER_STATE = 'RESET_REGISTER_STATE';
export const RESET_MATERIAL_COLLECTION_DATA = 'RESET_MATERIAL_COLLECTION_DATA';
export const RESET_PRODUCT_LIST_DATA = 'RESET_PRODUCT_LIST_DATA';
